### ISSUE TITLE
(Feature request) auto stretch

### ISSUE THREAD

**Issue by ubone** [otsaloma/gaupol#149]
could you add a key to auto stretch the start or end of a selected cell
to the end of the cell before it or the start of the cell after it

**Comment by otsaloma** [comment]
Why would you do that? What kind of a use case do you have or what kind of a workflow does that fit in?

**Comment by ubone** [comment]
> Why would you do that?

to avoid subtitle flicker
I'm not sure how to answer the latter but let's say I have a lot of text to fit in a limited time

**Comment by ubone** [comment]
basically if/when times are way off and you fix one of them it's easier and faster to just
click expand to end/start of previous/next

**Comment by otsaloma** [comment]
If you have a bad subtitle file with lots end times off, either too short or overlapping with the next, there's a batch tool for that under Tools / Adjust Durations. Does that do what you need? In general, if you need to make these kinds of dummy fixes, it makes more sense to me to have batch tools for that rather than manually doing the same thing one subtitle at a time.

If, on the other hand, you have start times off, then I don't really any kind of automated fixing helping there.
