### ISSUE TITLE
[possible bug]Open dialog issue

### ISSUE THREAD

**Issue by dancer69** [otsaloma/gaupol#163]
I'm using pop os 20.04, which is ubuntu based distro and I recently installed gaupol v1.8 via apt. I have an issue with open dialog. This open a gtk3 file select dialog which behaves different than this dialog when opens from another application. The problem is that when this dialog opens from another application as the default image viewer for example, I can have access to all directories, shortcuts, favorites and mounted partitions, but on gaupol appear only the user's home directory and the default directories(documents, video, downloads, images). All other shortcuts I've made in file manager and also all mounted partitions missed. And also when I use the "other places" there is nothing there except the "Computer", no other entries of mounted drives or anything. And when pressing the "Computer" entry, this doesn't display all directories of root folder "/". There also missed some folders including /mnt and /media in which are the video and subtitles files. If I open a subtitle file from file manager with gaupol, this file opens in gaupol, but I cannot open the video file which is in the same folder because gtk3 dialog doesn't have the entry of /media in which those files are.

**Comment by otsaloma** [comment]
Network drives are not accessible, that's a known issue: https://github.com/otsaloma/gaupol/issues/160

Anything mounted at a filesystem path, such as /media or /mnt, should work fine.

Are you sure you're using Gaupol installed via apt? In case you installed the Flatpak too, you might be using that without being able to tell the difference. I mention this because the Flatpak is sandboxed and has access to only the home directory and whatever is the default video directory. Rest of the filesystem comes from the Flatpak container and might look empty. The regular version installed via apt shouldn't have any sandboxing unless Pop OS is doing something weird.

**Comment by dancer69** [comment]
I installed it from synaptics package manager, but seems that was also installed via flatpak. I just removed the flatpak package and now I can see the /mnt, /media and all other missing places. I don't like this flatpak intergration and I'm thinking to move to linux mint because of this. Anyway, thanks for point that out, it was very helpful and fixed my problem.
