### ISSUE TITLE
How to install spellcheck for Gaupol app on Linux?

### ISSUE THREAD

**Issue by slrslr** [otsaloma/gaupol#176]
Hello,

if i want to install czech spell check for Gaupol on Linux Arch, how do i do it?
I do not see the explanation in documentation, nor in the Tools / Configure Spell-Check"

**Comment by otsaloma** [comment]
It's not mentioned in the documentation, because it's really complicated and varies by OS and distro. And there are some efforts by distros reduce that complexity so things might be in motion. Gaupol uses gspell, which uses enchant, which uses various backends (without telling you which one), which then use their own dictionaries.

gspell folks seem to recommend hunspell. On my Debian system, I'd install packages "hunspell" and "hunspell-en-us" etc.

https://gitlab.gnome.org/GNOME/gspell/-/blob/master/README#L32

**Comment by slrslr** [comment]
Thanks, that worked. On Arch/Manjaro Linux, i did "pamac search -a hunspell", it listed the czech package, and i installed it "pamac build hunspell-cs". Then after starting Gaupol, the czech dictionary was there and spell check worked.

**Comment by otsaloma** [comment]
I have wanted multiple languages too (#11), but it seemed complicated, so I gave up. It would be a lot easier if it was available upstream in gspell: https://gitlab.gnome.org/GNOME/gspell/-/issues/5
