### ISSUE TITLE
Spellcheck in Windows

### ISSUE THREAD

**Issue by rsaotome2k21** [otsaloma/gaupol#183]
Gaupol 1.3.1, spellcheck doesn't seem to have been installed, or just doesn't work.

After loading an .srt sub, tools -> correct texts works fine, but both check spelling & configure spell-check is greyed out.

Did I do something wrong?

**Comment by otsaloma** [comment]
It's quite a while since I still did those Windows installers, so I don't remember the exact status anymore, but it doesn't sound surprising, you didn't really do anything wrong. It's possible you have some conflicting enchant DLLs in PATH, but I think there was some conflicts inside Gaupol as well (GtkSpell/PyEnchant).
