### ISSUE TITLE
Gst not found on Windows

### ISSUE THREAD

**Issue by ZeaZon21** [otsaloma/gaupol#190]
Hello! I'm just installed this program, open subs and tried to open video. After that I got this error

Traceback

File: C:\Users\osa\Desktop\gaupol-1.3.1\gaupol\agents\open.py
Line: 196
In: _on_notebook_drag_data_received

    

File: C:\Users\osa\Desktop\gaupol-1.3.1\gaupol\agents\video.py
Line: 161
In: load_video

    

File: C:\Users\osa\Desktop\gaupol-1.3.1\gaupol\agents\video.py
Line: 129
In: _init_player_widgets

    

File: C:\Users\osa\Desktop\gaupol-1.3.1\gaupol\player.py
Line: 72
In: __init__

    

File: C:\Users\osa\Desktop\gaupol-1.3.1\gaupol\player.py
Line: 187
In: _init_text_overlay

    

NameError: name 'Gst' is not defined

Environment

Platform: Windows-10-10.0.19041
Locale: en_US.cp1252

Versions

aeidon: 1.3.1
chardet: 2.3.0
enchant: None
gaupol: 1.3.1
gstreamer: None
gtk+: 3.18.9
pygobject: 3.24.1
python: 3.4.4

**Comment by otsaloma** [comment]
The Windows version doesn't include the built-in video player, because I never got it to work on Windows. The menu and toolbar items related to the built-in video player should be grayed out, but apparently I have missed the video file drag-and-drop. The packaging is not going to be fixed (see #189), so best I can tell you is: Don't drag-and-drop video files.
