### ISSUE TITLE
The Undo dropmarker is enabled yet when no documents are open

### ISSUE THREAD

**Issue by nohamelin** [otsaloma/gaupol#29]
Hi,
Giving a try to the current gaupol from git in a live session of Fedora 24 Workstation (from _Fedora-Workstation-Live-i386-24-1.2.iso_):

* Open gaupol.
* Note that, even if no documents are open, the dropmarker of the Undo button is not disabled, though the Undo button itself is disabled.
* Clicking the dropmarker triggers the next error:

> File: /home/liveuser/Descargas/gaupol-0.91/gaupol/agents/menu.py
> Line: 165
> In: _on_undo_button_show_menu
> 
>     for i, action in enumerate(page.project.undoables):
> 
> AttributeError: 'NoneType' object has no attribute 'project'
> 
> Environment
> 
> Platform: Linux-4.5.5-300.fc24.i686-i686-with-fedora-24-Twenty_Four
> Locale: es_ES.utf_8
> 
> Versions
> 
> aeidon: 0.91
> chardet: 2.2.1
> enchant: 1.6.6
> gaupol: 0.91
> gstreamer: 1.8.1.0
> gtk+: 3.20.6
> pygobject: 3.20.1
> python: 3.5.1

I didn't try to update the system of the live session, so I don't know if the involved packages are really up-to-date.

**Comment by otsaloma** [comment]
I did already earlier notice that after porting to `Gio.Action` etc. the undo button displays a blank menu when a document is open, but there's nothing to undo yet. Ugly, but not a big deal. I didn't notice what happens when no document is open. I'll fix the bug you see.

The button itself follows the state of the undo action via `Gtk.Actionable.set_action_name`, but for some reason not the dropdown arrow. Probably an oversight or bug in GTK+, but I don't care to investigate further.
