### ISSUE TITLE
Confirming the "Save file" dialog via Enter doesn't add a missing extension as the "Save" button does

### ISSUE THREAD

**Issue by nohamelin** [otsaloma/gaupol#32]
Giving a try to the current gaupol from git in a live session of Fedora 24 Workstation:

* Create a new document, then trigger the "save" action: the save dialog is opened. 
* Write some name for the file, without to specify any extension. Note here that the "SubRip" format is selected by default in the respective drop-down menu.
* Still having the focus in the filename box, press Enter. The file is created with the given name without any extension; If I would chosen to click in the Save button to confirm the action, the created file would have the extension .srt, as it corresponds to the selected format.

**Comment by otsaloma** [comment]
Long ago I ended up connecting to "event" of the save button to add the extension. That would mean _any_ event; when using a mouse it would be hovering or clicking; when using a keyboard it at least used to be so that the save button experienced a focus-in-event thus adding the extension before saving.

The reason for the ugly way is that the extension needs to be added before the save dialog's internal file overwrite check and possible confirmation dialog and I found no clean way to connect before that, the intended "confirm-overwrite" signal didn't work as expected. Things might be better now, I'll check.

**Comment by otsaloma** [comment]
The "confirm-overwrite" only gets called when the file already exists, so connecting to that didn't help. There still doesn't seem to be a clear way to do this, but stopping the response, adding the extension and emitting a new response should get the job done correctly. This is a bit ugly too, but seemed to work all right.
