### ISSUE TITLE
Add action Set Start From Video Position

### ISSUE THREAD

**Issue by Fornost461** [otsaloma/gaupol#53]
To complement _Set End From Video Position_ (in the `Edit` menu, or shortcut `K`). This could be helpful to deal with out-of-sync subtitles, especially if the function _Seek backward/forward_ was made more powerful (by allowing not just big jumps, but also 50-100ms jumps).

**Comment by otsaloma** [comment]
The way I have thought about it is that you'd set the start time by using Edit / Stretch / Start Earlier (<kbd>Q</kbd>) and Start Later (<kbd>W</kbd>). And then you could alternate fast-pace between pressing <kbd>Q</kbd> / <kbd>W</kbd> to edit and <kbd>O</kbd> to check the result. Does that suit your use case and workflow?

https://github.com/otsaloma/gaupol/blob/master/doc/creating-subtitles.md

Setting the start time from video position is difficult because for a single subtitle you'd need, as you suggest, more jump features or some other way to start playback near where you want it, or for multiple subtitles some kind of selection tracking. And you'd still be off by your reaction time and would need to do fine-tuning a different way, such as the above <kbd>Q</kbd> and <kbd>W</kbd>.

**Comment by Fornost461** [comment]
This is already what I was doing, because I had read this very helpful documentation file. I do not ask for a new jump feature, but for a modification of the existing one, which currently can only be set to an integer number of seconds in the preferences (section Video), instead of a float value. I think that a float value for it, coupled with Set Start From Video Position, could make my work faster.

I do not understand what you mean about making this feature work with multiple subtitles. I believe the existing similar feature, Set End From Video Position (`K`), does not handle multiple subtitles at a time.

A new suggestion: add an option in the preferences to make Set End From Video Position (`K`) automatically select the next subtitle and unselect the subtitle whose end was just actualized.

Whether you decide to implement any of this or not, your software remains the best I found for my purposes, so thank you very much anyway.

**Comment by otsaloma** [comment]
I'll give this some more thought and return to it later. Your suggestion does make sense, it's not difficult to implement and it won't clutter the menu. Mostly I'm worried about having consistent and sensible keybindings that support a keyboard-based workflow. GTK+ used to have user-configurable keybindings, but now that that's no longer true (to my knowledge), I need to be particularly careful with the choices.

> I do not understand what you mean about making this feature work with multiple subtitles. I believe the existing similar feature, Set End From Video Position (K), does not handle multiple subtitles at a time.

You are correct. For me, "Insert subtitle at video position" is the more logical comparison and also setting the start time roughly correct to be a prerequisite for other edits, something preferrably done a batch at a time.

> New suggestion: add an option in the preferences to make Set End From Video Position (K) automatically unselect the current subtitle and select the next one instead.

For this, I'd say no. People will do the individual edits in a slightly different order and some of them multiple times, meaning there's a lot of different conditions for when people would want the selection moved down.

**Comment by Fornost461** [comment]
I discovered that Shift Positions (`H`) was even more useful in my situation than would be Set Start From Video Position (I noticed that my reaction time is relatively consistent), so it no longer matters to me whether the possible features we talked about here will be implemented.

**Comment by otsaloma** [comment]
OK, I think I'll skip this.
