### ISSUE TITLE
Disable autoplay

### ISSUE THREAD

**Issue by Fornost461** [otsaloma/gaupol#57]
Whenever I load a video, the first thing I do is press the pause button. Please disable autoplay or add an option to disable it through the preferences. Thank you.

**Comment by otsaloma** [comment]
Autoplay is for two reasons: (1) because most videos start with a black frame and that just looks blank and users might be confused as to whether the video was loaded or not and (2) to detect playback problems (missing codecs etc.) you need to not just load the video, but also try to play it and it's best to be able to report playback problems immediately.

Maybe I could add a hidden option, i.e. not included in the preferences dialog, but would be in the configuration file. Would that be OK?

**Comment by Fornost461** [comment]
Yes, that would be great, thank you.
