### ISSUE TITLE
Could not start the program ('PyGObjectParamFlags' has no attribute 'READWRITE')

### ISSUE THREAD

**Issue by hlovdahl** [otsaloma/gaupol#65]
I downloaded using the link-button on the webpage, installed intltools and then run the installer. When I tried to start the program it said the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/gaupol", line 17, in <module>
    import gaupol
  File "/usr/local/lib/python3.4/dist-packages/gaupol/__init__.py", line 65, in <module>
    from gaupol.renderers import *
  File "/usr/local/lib/python3.4/dist-packages/gaupol/renderers/__init__.py", line 22, in <module>
    from .multiline import MultilineCellRenderer
  File "/usr/local/lib/python3.4/dist-packages/gaupol/renderers/multiline.py", line 31, in <module>
    class CellTextView(Gtk.TextView, Gtk.CellEditable):
  File "/usr/local/lib/python3.4/dist-packages/gaupol/renderers/multiline.py", line 40, in CellTextView
    GObject.ParamFlags.READWRITE),
AttributeError: type object 'PyGObjectParamFlags' has no attribute 'READWRITE'
```

**Comment by otsaloma** [comment]
Which version of which distro are you using?

Could you run the following Python script to check versions of the dependencies? 

```python
#!/usr/bin/env python3
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import GObject, Gtk
print(GObject.pygobject_version)
print((Gtk.get_major_version(),
       Gtk.get_minor_version(),
       Gtk.get_micro_version()))
```

**Comment by hlovdahl** [comment]
I'm running Ubuntu 14.04.

Here's the output from the script:

python3 test_version.py 
(3, 12, 0)
(3, 10, 8)

**Comment by hlovdahl** [comment]
It did work on my other computer where I run Ubuntu 16.04.

**Comment by otsaloma** [comment]
I seem to have migrated away from deprecated properties and maybe misunderstood which version of (Py)GObject that implied.

https://github.com/otsaloma/gaupol/commit/684e2f0922587a760623fd2b8228df577bfddb5a

I can't easily now tell what the version dependency is or if it's GObject or PyGObject, nor do I care to investigate much matters of older versions. And even though you seem to have run into issues with GObject, the latest version of Gaupol requires GTK+ 3.12, while you have 3.10, so there'd be other problems too.

My advice for Ubuntu 14.04 is that you try the release before that above commit, 0.28.2, or the version in Ubuntu's repositories, 0.24.3.

These various dependency issues are due to GLib/GObject/GTK+ 3 being too much of a fast moving target. With the new [versioning system](https://blog.gtk.org/2016/09/01/versioning-and-long-term-stability-promise-in-gtk/), these problems are hopefully in the past.
