### ISSUE TITLE
"language" from "audio" menu is active even when no video is open

### ISSUE THREAD

**Issue by glaubersm** [otsaloma/gaupol#72]
Hi
I use gaupol on Arch Linux, title says by itself.
Furthermore an empty submenu appears on mouseover "language" from "audio" menu.

![peek2](https://user-images.githubusercontent.com/15967631/34079733-77fbf212-e31a-11e7-86fd-de2b8038502c.gif)

**Comment by otsaloma** [comment]
Yes, I know, it's been like that since 0.91 after migrating to the newer GTK+ action and menu systems `GAction`, `GMenu` etc. They just don't seem to support dynamics as well as `GtkUImanager` did (or to be exact, it would be much more difficult to accomplish the same as what was easily done before). So, that's just how it is.
