### ISSUE TITLE
Built-in video player does not work with Haswell chipset

### ISSUE THREAD

**Issue by ktamp** [otsaloma/gaupol#79]
With **Gaupol v1.3.0** or **v1.3.1** on a computer with Intel Haswell integrated graphics running 64bit Arch Linux, the built-in video player does not work. Neither it crushes nor some error message is displayed. It just does not work. This applies to both Xorg and Wayland sessions.

With **Gaupol v1.2** (and Xorg) on the same computer, the built-in video player works.

With **Gaupol v1.3.1** on a different computer with the same software setup and an old integrated Intel GMA graphics chipset, the built-in video player works!

If there is some test or experimental code I could try, please let me know.

**Comment by otsaloma** [comment]
Gaupol 1.3 switched to use GStreamer's gtksink instead of autovideosink. The change was made so that the video player would work on Wayland too (and potentially Windows), while autovideosink worked only on X.

I did not note it, but that might have brought on some GPU requirement ("gl"). But, I wonder if you're just missing some drivers?, that would be the easiest solution.

**Comment by ktamp** [comment]
Both systems have the same drivers installed. However, the problem is indeed driver (or **gstreamer**) related. That is, if **gstreamer-vaapi** is installed **and** used by **gstreamer**, **gaupol v1.3.x** (using **gtksink**) fails. So, removing **gstreamer-vaapi** solves the issue.

When **gstreamer-vaapi** is installed and Xorg is used, you can tell if **vaapi** is used by **gstreamer** by successfully running:
`gst-launch-1.0 filesrc location=<your video> ! decodebin ! autovideosink`

When **gstreamer-vaapi** is not installed and Xorg is used, the previous command always succeeds.

Curiously enough, the following command always fails:
`gst-launch-1.0 filesrc location=<your video> ! decodebin ! gtksink`

**Comment by otsaloma** [comment]
Now that I checked and remember, GStreamer also has "gtkglsink" and I specifically chose to use "gtksink" instead, assuming it would be a safer choice – and it probably is.

Anyway, this sounds like a more general issue, if you want to see some kind of a fix, maybe report it to GStreamer or Arch? There seems to be a [bug report](https://bugs.archlinux.org/task/47256?project=1&string=gstreamer-vaapi) on Arch, but I can't tell if it's the same thing.

**Comment by ktamp** [comment]
It appears that, when **gstreamer-vaapi** is employed, **vaapisink** should be used. So simply dismissing **autovideosink** (which automatically selects the correct sink) may not be such a good idea after all.

**Comment by otsaloma** [comment]
The trouble with autovideosink was rendering the video in a GTK+ widget. It required some weird dance with sync messages and window handles, which never worked on Windows due to missing GI bindings and looked like too much work and a pile of special-cased code to replicate for Wayland.

https://github.com/otsaloma/gaupol/commit/dee6b6544e6ba2d26f287d46a13a731c48fa1c9f

**Comment by otsaloma** [comment]
gst-vaapi is now disabled via environment variables during init, so Gaupol should just work whether you have gst-vaapi installed or not.

https://github.com/otsaloma/gaupol/commit/563874d9d3c5ea50bdcb40fc9dfe5e2d2f5d3816
