### ISSUE TITLE
Ability to add text on top of the screen?

### ISSUE THREAD

**Issue by WPFilmmaker** [otsaloma/gaupol#85]
Combined with #84 it would be great for adding notes for the viewers.

**Comment by otsaloma** [comment]
I vaguely recall this kind of positioning is only reasonably supported by some of the more complicated formats, with unreasonable support meaning pixel coordinates instead something simple like `position="top"`. I would personally find postioning useful so that subtitles could "dodge" something part of the video, e.g. beginning credits. But, the lacking file format support makes low-priority or unlikely, maybe I'll check the support at some point.

**Comment by otsaloma** [comment]
I checked the file-format support. (Advanced) Sub Station Alpha (ASS/SSA) has support for a complicated alignment field, which includes "toptitles", and the rarely seen extended SubRip has support for pixel coordinates. I don't think it's worth the trouble.
